services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../:/src
      - /src/node_modules
    command: sh -c "npm install && npm run dev"
